- name: Install update and upgrade
  hosts: all
  tasks:
    -  name: Install update and upgrade
       apt: upgrade=dist force_apt_get=yes
    -  name: Check if a reboot is needed for Debian and Ubuntu
       register: reboot_required_file
       stat: path=/var/run/reboot-required get_md5=no